new file updated

diff --git a/.github/workflows/rat.yaml b/.github/workflows/rat.yaml
--- a/.github/workflows/rat.yaml
+++ b/.github/workflows/rat.yaml
@@ -1,4 +1,4 @@
-name: Step 2 - Receive Application Trigger
+name: SecOps Pipeline
 
 on:
   repository_dispatch:
@@ -7,22 +7,22 @@ on:
 
 jobs:
 
-  # ==================================================
-  # Stage 1: Gitleaks Secret Scanning
-  # ==================================================
+  # =========================================================
+  # Stage 1: Secret Scanning
+  # =========================================================
   gitleaks:
     name: Gitleaks - Secret Scanning
     runs-on: ubuntu-latest
 
     steps:
 
-      # --------------------------------------------------
-      # Step 1: Display received application information
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 1: Display Application Information
+      # -------------------------------------------------------
       - name: Display Received Application Information
         run: |
           echo "=========================================="
-          echo "SecOps Repo Received Application Trigger"
+          echo "SecOps Repo received Application trigger"
           echo "=========================================="
 
           echo "Application Repository: ${{ github.event.client_payload.repository }}"
@@ -31,9 +31,9 @@ jobs:
           echo "Event Type: ${{ github.event.action }}"
 
 
-      # --------------------------------------------------
-      # Step 2: Checkout exact application commit
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 2: Checkout Exact Application Commit
+      # -------------------------------------------------------
       - name: Checkout Exact Application Commit
         uses: actions/checkout@v4
         with:
@@ -43,9 +43,9 @@ jobs:
           path: application
 
 
-      # --------------------------------------------------
-      # Step 3: Verify checked out commit
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 3: Verify Checked Out Commit
+      # -------------------------------------------------------
       - name: Verify Checked Out Commit
         run: |
           echo "=========================================="
@@ -59,9 +59,9 @@ jobs:
           git -C application rev-parse HEAD
 
 
-      # --------------------------------------------------
-      # Step 4: Scan application for leaked secrets
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 4: Gitleaks Secret Scan
+      # -------------------------------------------------------
       - name: Step 4 - Scan for Application Secrets
         run: |
           docker run --rm \
@@ -76,31 +76,30 @@ jobs:
             --exit-code 1
 
 
-      # --------------------------------------------------
-      # Step 4A: Show detected secrets
-      # --------------------------------------------------
-      - name: Step 4A - Show Detected Secrets
+      # -------------------------------------------------------
+      # Step 5: Show Gitleaks Findings
+      # -------------------------------------------------------
+      - name: Step 5 - Show Detected Secrets
         if: always()
         run: |
           echo "Gitleaks Findings:"
           echo "====================================="
 
           if [ -f "application/gitleaks-report.json" ]; then
-
             cat application/gitleaks-report.json | jq -r '
               .[] |
               "File: \(.File)\nLine: \(.StartLine)\nRule: \(.RuleID)\nSecret: \(.Match)\nCommit: \(.Commit // "N/A")\n---"
             '
-
           else
-            echo "No report file found — either no secrets were detected or the scan did not run."
+            echo "No report file found."
           fi
 
 
-      # --------------------------------------------------
-      # Step 4B: List scanned files
-      # --------------------------------------------------
-      - name: Step 4B - List Scanned Files
+      # -------------------------------------------------------
+      # Step 6: List Scanned Files
+      # -------------------------------------------------------
+      - name: Step 6 - List Scanned Files
+        if: always()
         run: |
           echo "Files Inside Gitleaks Scanning Scope:"
           echo "====================================="
@@ -108,10 +107,22 @@ jobs:
           find application -type f -print
 
 
-  # ==================================================
-  # Stage 2: Trivy Dependency Scanning
-  # ==================================================
-  trivy:
+      # -------------------------------------------------------
+      # Step 7: Upload Gitleaks Report
+      # -------------------------------------------------------
+      - name: Upload Gitleaks Report
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: gitleaks-report
+          path: application/gitleaks-report.json
+          if-no-files-found: ignore
+
+
+  # =========================================================
+  # Stage 2: Dependency Scanning
+  # =========================================================
+  trivy-deps:
     name: Trivy - Dependency Scanning
     runs-on: ubuntu-latest
 
@@ -119,13 +130,14 @@ jobs:
 
     steps:
 
-      # --------------------------------------------------
-      # Step 1: Display application information
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 1: Display Application Information
+      # -------------------------------------------------------
       - name: Display Received Application Information
         run: |
           echo "=========================================="
           echo "SecOps Repo received Application trigger"
+          echo "for dependency scan"
           echo "=========================================="
 
           echo "Application Repository: ${{ github.event.client_payload.repository }}"
@@ -133,9 +145,9 @@ jobs:
           echo "Application Commit SHA: ${{ github.event.client_payload.commit_sha }}"
 
 
-      # --------------------------------------------------
-      # Step 2: Checkout exact application commit
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 2: Checkout Exact Application Commit
+      # -------------------------------------------------------
       - name: Checkout Exact Application Commit
         uses: actions/checkout@v4
         with:
@@ -145,25 +157,23 @@ jobs:
           path: application
 
 
-      # --------------------------------------------------
-      # Step 3: Verify checked out commit
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 3: Verify Checked Out Commit
+      # -------------------------------------------------------
       - name: Verify Checked Out Commit
         run: |
-          echo "=========================================="
           echo "Application Source Successfully Checked Out"
-          echo "=========================================="
 
           echo "Expected Commit:"
           echo "${{ github.event.client_payload.commit_sha }}"
 
-          echo "Actual Checked Out Commit:"
+          echo "Actual Commit:"
           git -C application rev-parse HEAD
 
 
-      # --------------------------------------------------
-      # Step 4: Scan dependencies using Trivy
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 4: Trivy Dependency Scan
+      # -------------------------------------------------------
       - name: Step 4 - Scan Dependencies for Vulnerabilities
         run: |
           docker run --rm \
@@ -178,9 +188,9 @@ jobs:
             --exit-code 1
 
 
-      # --------------------------------------------------
-      # Step 5: Generate JSON report
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 5: Generate Trivy JSON Report
+      # -------------------------------------------------------
       - name: Step 5 - Generate JSON Report of Findings
         if: always()
         run: |
@@ -193,40 +203,189 @@ jobs:
             --scanners vuln \
             --severity CRITICAL,HIGH \
             --format json \
-            --output /repo/trivy-report.json \
+            --output /repo/trivy-fs-report.json \
             --exit-code 0
 
 
-      # --------------------------------------------------
-      # Step 6: Show vulnerability summary
-      # --------------------------------------------------
+      # -------------------------------------------------------
+      # Step 6: Show Vulnerability Summary
+      # -------------------------------------------------------
       - name: Step 6 - Show Vulnerability Summary
         if: always()
         run: |
-          echo "====================================="
           echo "Trivy Dependency Findings:"
           echo "====================================="
 
-          if [ -f "application/trivy-report.json" ]; then
+          if [ -f "application/trivy-fs-report.json" ]; then
 
-            cat application/trivy-report.json | jq -r '
-              .Results[]? |
-              select(.Vulnerabilities != null) |
-              .Vulnerabilities[] |
-              "Package: \(.PkgName)\nInstalled: \(.InstalledVersion)\nFixed In: \(.FixedVersion // "N/A")\nSeverity: \(.Severity)\nCVE: \(.VulnerabilityID)\n---"
+            cat application/trivy-fs-report.json | jq -r '
+              .Results[]?
+              | select(.Vulnerabilities != null)
+              | .Vulnerabilities[]
+              | "Package: \(.PkgName)\nInstalled: \(.InstalledVersion)\nFixed In: \(.FixedVersion // "N/A")\nSeverity: \(.Severity)\nCVE: \(.VulnerabilityID)\n---"
             '
 
           else
-            echo "No report file found — either no vulnerable dependencies were detected or the scan did not run."
+            echo "No report file found."
           fi
 
 
-      # --------------------------------------------------
-      # Step 7: Upload Trivy report
-      # --------------------------------------------------
-      - name: Upload Trivy Report Artifact
+      # -------------------------------------------------------
+      # Step 7: Upload Trivy FS Report
+      # -------------------------------------------------------
+      - name: Upload Trivy FS Report Artifact
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: trivy-dependency-report
-          path: application/trivy-report.json
+          path: application/trivy-fs-report.json
+          if-no-files-found: ignore
+
+
+  # =========================================================
+  # Stage 3: Docker Image Build + Image Scanning
+  # =========================================================
+  build-and-scan-image:
+    name: Build & Scan Docker Image
+    runs-on: ubuntu-latest
+
+    needs: trivy-deps
+
+    steps:
+
+      # -------------------------------------------------------
+      # Step 1: Display Application Information
+      # -------------------------------------------------------
+      - name: Display Received Application Information
+        run: |
+          echo "=========================================="
+          echo "SecOps Repo received Application trigger"
+          echo "for image build & scan"
+          echo "=========================================="
+
+          echo "Application Repository: ${{ github.event.client_payload.repository }}"
+          echo "Application Branch: ${{ github.event.client_payload.branch }}"
+          echo "Application Commit SHA: ${{ github.event.client_payload.commit_sha }}"
+
+
+      # -------------------------------------------------------
+      # Step 2: Checkout Exact Application Commit
+      # -------------------------------------------------------
+      - name: Checkout Exact Application Commit
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.event.client_payload.repository }}
+          ref: ${{ github.event.client_payload.commit_sha }}
+          token: ${{ secrets.APPLICATION_REPO_READ_TOKEN }}
+          path: application
+
+
+      # -------------------------------------------------------
+      # Step 3: Verify Checked Out Commit
+      # -------------------------------------------------------
+      - name: Verify Checked Out Commit
+        run: |
+          echo "Application Source Successfully Checked Out"
+
+          echo "Expected Commit:"
+          echo "${{ github.event.client_payload.commit_sha }}"
+
+          echo "Actual Commit:"
+          git -C application rev-parse HEAD
+
+
+      # -------------------------------------------------------
+      # Step 4: Verify Dockerfile
+      # -------------------------------------------------------
+      - name: Verify Dockerfile
+        run: |
+          echo "Checking backend Dockerfile..."
+
+          if [ -f "application/backend/Dockerfile" ]; then
+            echo "Dockerfile found:"
+            ls -lh application/backend/Dockerfile
+          else
+            echo "ERROR: application/backend/Dockerfile not found!"
+            exit 1
+          fi
+
+
+      # -------------------------------------------------------
+      # Step 5: Build Docker Image
+      # -------------------------------------------------------
+      - name: Step 5 - Build Docker Image
+        run: |
+          docker build \
+            -t hireflow-backend:${{ github.event.client_payload.commit_sha }} \
+            -f application/backend/Dockerfile \
+            application/backend
+
+
+      # -------------------------------------------------------
+      # Step 6: Scan Docker Image
+      # -------------------------------------------------------
+      - name: Step 6 - Scan Docker Image for Vulnerabilities
+        run: |
+          docker run --rm \
+            -v /var/run/docker.sock:/var/run/docker.sock \
+            -v "${GITHUB_WORKSPACE}/trivy-cache:/root/.cache/" \
+            aquasec/trivy:latest \
+            image \
+            hireflow-backend:${{ github.event.client_payload.commit_sha }} \
+            --severity CRITICAL,HIGH \
+            --format table \
+            --exit-code 1
+
+
+      # -------------------------------------------------------
+      # Step 7: Generate Image JSON Report
+      # -------------------------------------------------------
+      - name: Step 7 - Generate JSON Report of Image Findings
+        if: always()
+        run: |
+          docker run --rm \
+            -v /var/run/docker.sock:/var/run/docker.sock \
+            -v "${GITHUB_WORKSPACE}/trivy-cache:/root/.cache/" \
+            -v "${GITHUB_WORKSPACE}:/output" \
+            aquasec/trivy:latest \
+            image \
+            hireflow-backend:${{ github.event.client_payload.commit_sha }} \
+            --severity CRITICAL,HIGH \
+            --format json \
+            --output /output/trivy-image-report.json \
+            --exit-code 0
+
+
+      # -------------------------------------------------------
+      # Step 8: Show Image Vulnerability Summary
+      # -------------------------------------------------------
+      - name: Step 8 - Show Image Vulnerability Summary
+        if: always()
+        run: |
+          echo "Trivy Image Scan Findings:"
+          echo "====================================="
+
+          if [ -f "trivy-image-report.json" ]; then
+
+            cat trivy-image-report.json | jq -r '
+              .Results[]?
+              | select(.Vulnerabilities != null)
+              | .Vulnerabilities[]
+              | "Package: \(.PkgName)\nInstalled: \(.InstalledVersion)\nFixed In: \(.FixedVersion // "N/A")\nSeverity: \(.Severity)\nCVE: \(.VulnerabilityID)\n---"
+            '
+
+          else
+            echo "No report file found."
+          fi
+
+
+      # -------------------------------------------------------
+      # Step 9: Upload Trivy Image Report
+      # -------------------------------------------------------
+      - name: Upload Trivy Image Report Artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-image-report
+          path: trivy-image-report.json
+          if-no-files-found: ignore
